from __future__ import annotations

import pytest
import torch

from evaluation.global_probe import (
    GlobalProbeInputs,
    GlobalReadoutGeometry,
    fit_global_probe,
)
from training.state import (
    RepresentationSelectionMetrics,
    ValidationState,
)


def test_global_probe_cross_validates_only_two_polarity_gains() -> None:
    # Given: three sources generated by a shared two-gain tied readout.
    readout = torch.tensor(
        [
            [[[1.0], [0.0]], [[2.0], [0.0]]],
            [[[0.0], [1.0]], [[0.0], [2.0]]],
            [[[1.0], [1.0]], [[2.0], [2.0]]],
        ]
    )
    target = 2.0 * readout[:, :, 0] - 3.0 * readout[:, :, 1]
    geometry = GlobalReadoutGeometry(
        spatial_weights=torch.ones(1, 1),
        gain_max=5.0,
    )

    # When: the low-capacity global probe is source-cross-validated.
    result = fit_global_probe(
        GlobalProbeInputs(
            train_readout=readout,
            train_target=target,
            train_source_ids=("a", "b", "c"),
            validation_readout=readout,
            validation_target=target,
            validation_source_ids=("a", "b", "c"),
        ),
        geometry,
    )

    # Then: held-out reconstruction is exact without per-unit gains.
    assert result.source_cv_mse == pytest.approx(0.0, abs=1e-10)
    assert result.validation_mse == pytest.approx(0.0, abs=1e-10)
    assert len(result.validation_source_mse) == 3


def test_representation_checkpoint_requires_generator_and_validation_guards() -> None:
    # Given: a fresh validation state and guarded representation candidates.
    state = ValidationState()

    # When: candidates improve rate CV with and without guard satisfaction.
    generator_failed = state.observe_representation(
        RepresentationSelectionMetrics(
            rate_source_cv_ratio=0.95,
            generator_source_cv_ratio=1.02,
            fixed_validation_ratio=1.00,
        )
    )
    validation_failed = state.observe_representation(
        RepresentationSelectionMetrics(
            rate_source_cv_ratio=0.94,
            generator_source_cv_ratio=1.00,
            fixed_validation_ratio=1.03,
        )
    )
    accepted = state.observe_representation(
        RepresentationSelectionMetrics(
            rate_source_cv_ratio=0.96,
            generator_source_cv_ratio=1.00,
            fixed_validation_ratio=1.01,
        )
    )

    # Then: only the guarded candidate becomes the representation checkpoint.
    assert not generator_failed
    assert not validation_failed
    assert accepted
    assert state.best_representation_rate_ratio == pytest.approx(0.96)
