from __future__ import annotations

import numpy as np
import pytest

from evaluation.mechanistic_retina.karamanlis_rf_centers import (
    RFGrid,
    RFSuccess,
    estimate_rf,
    recreate_binary_white_noise,
    spike_triggered_average,
)
from evaluation.mechanistic_retina.karamanlis_running_sta import StreamingSTA
from evaluation.mechanistic_retina.gollisch_white_noise import (
    initialize_ran1,
    recreate_binary_white_noise_block,
)


def test_binary_white_noise_matches_official_matlab_mex() -> None:
    # Given: a sequence independently generated by the Gollisch Lab MATLAB MEX.
    seed = -1000
    expected = np.asarray(
        [
            [[-1, 1, 1, 1], [-1, -1, 1, -1], [1, 1, 1, 1]],
            [[-1, -1, 1, -1], [1, -1, 1, -1], [-1, 1, -1, -1]],
        ],
        dtype=np.int8,
    )

    # When: the same seed and x/y/frame dimensions are reconstructed locally.
    stimulus = recreate_binary_white_noise(seed, 4, 3, 2)

    # Then: values and the bottom-up y-axis orientation agree element by element.
    assert np.array_equal(stimulus, expected)


def test_spike_triggered_average_uses_past_stimulus_lags() -> None:
    # Given: one spike whose preceding two scalar stimuli are known exactly.
    stimulus = np.arange(5, dtype=np.float32).reshape(5, 1, 1)
    response = np.asarray([0, 0, 0, 1, 0], dtype=np.float64)

    # When: a two-lag STA is computed.
    sta = spike_triggered_average(stimulus, response, lag_count=2)

    # Then: lag zero is current-frame stimulus and lag one is one frame earlier.
    assert sta[:, 0, 0] == pytest.approx((1.0, 0.0))


def test_paper_projection_recovers_known_spatial_center() -> None:
    # Given: a separable spatiotemporal STA with a known Gaussian RF center.
    y, x = np.mgrid[0:17, 0:19]
    spatial = np.exp(-((x - 12.0) ** 2 + (y - 6.0) ** 2) / (2 * 2.0**2))
    temporal = np.asarray([-0.2, 0.6, 1.0, 0.4], dtype=np.float64)
    sta = temporal[:, None, None] * spatial[None]
    grid = RFGrid(
        x_centers_px=np.arange(19, dtype=np.float64),
        y_centers_px=np.arange(17, dtype=np.float64),
        stixel_width_px=1,
        stixel_height_px=1,
    )

    # When: the paper-style temporal projection and 25% contour are applied.
    estimate = estimate_rf(sta, grid)

    # Then: the contour median lies at the generating RF center.
    assert isinstance(estimate, RFSuccess)
    assert estimate.center_x_px == pytest.approx(12.0, abs=0.6)
    assert estimate.center_y_px == pytest.approx(6.0, abs=0.6)
    assert estimate.significant_pixel_count > 0


def test_stateful_rng_blocks_equal_one_continuous_sequence() -> None:
    # Given: one official ran1 state shared across consecutive stimulus blocks.
    state = initialize_ran1(-1000)

    # When: two blocks are reconstructed without resetting the seed.
    first, state = recreate_binary_white_noise_block(state, 2, 2, 3)
    second, _ = recreate_binary_white_noise_block(state, 2, 2, 4)

    # Then: their concatenation equals a single seven-frame reconstruction.
    whole = recreate_binary_white_noise(-1000, 2, 2, 7)
    assert np.array_equal(np.concatenate((first, second)), whole)


def test_streaming_sta_preserves_trial_boundaries_and_empirical_mean() -> None:
    # Given: two separate white-noise trials and their measured spike counts.
    stimuli = (
        np.asarray([-1, 1, -1, 1], dtype=np.float32).reshape(4, 1, 1),
        np.asarray([1, 1, -1, -1], dtype=np.float32).reshape(4, 1, 1),
    )
    responses = (
        np.asarray([0, 0, 1, 0], dtype=np.float32)[:, None],
        np.asarray([0, 1, 0, 0], dtype=np.float32)[:, None],
    )

    # When: both trials are accumulated with a two-bin RF lag window.
    accumulator = StreamingSTA.empty(2, 1, 1, 1)
    for stimulus, response in zip(stimuli, responses, strict=True):
        accumulator.add(stimulus, response)

    # Then: the conditional stimulus mean is centered without cross-trial lags.
    sta = accumulator.finalize()
    np.testing.assert_allclose(sta[:, :, 0, 0], np.asarray([[0.0, 1.0]]))
